language: node_js
node_js:
  - "stable"
install: npm install
services:
  - postgresql
before_script:
  - psql -c 'create database test_db;' -U postgres
  - npx knex migrate:down --env=testing
  - npx knex migrate:up --env=testing
script: npm test
after_success:
  - npx knex migrate:down --env=testing
  - npx knex migrate:up --env=testing
  - npm run coveralls
